dist: trusty
sudo: false

language: go
go_import_path: github.com/temporalio/sqlparser
go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.20.x
  - 1.21.x

before_install:
  - cd $GOPATH/src/github.com/temporalio/sqlparser

script:
  - go version
  - go test -v -cover ./...
